server:
  port: 8081

spring:
   application:
     name: WELCOME-API
   boot:
      admin:
        client:
          url: http://127.0.0.1:1111/
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'